# Generated by Django 5.2.8 on 2025-12-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0002_remove_medication_feedtime_alter_food_descr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recordDate', models.DateField()),
                ('descr', models.TextField(null=True)),
                ('forPet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medrec_for_pet', to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomType', models.CharField(max_length=200)),
                ('extraInfo', models.TextField(null=True)),
                ('dateAndTime', models.DateTimeField()),
                ('forPet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_for_pet', to='pet.pet')),
            ],
        ),
    ]
