# Generated by Django 5.2.8 on 2025-12-06 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0002_remove_medication_feedtime_alter_food_descr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descr', models.TextField(null=True)),
                ('due', models.DateTimeField()),
                ('isComplete', models.BooleanField(default=False)),
                ('forPet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_for_pet', to='pet.pet')),
            ],
        ),
    ]
