# Generated by Django 5.2.8 on 2025-12-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descr',
            field=models.TextField(blank=True, default='Insert description here'),
        ),
    ]
