# Generated by Django 5.2.8 on 2025-12-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descr',
            field=models.TextField(null=True),
        ),
    ]
