# Generated by Django 5.2.8 on 2025-12-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=50)),
                ('animalType', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('breed', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('exerciseReq', models.FloatField()),
                ('belongsToHouse', models.CharField(max_length=50)),
                ('belongsToBusiness', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medName', models.CharField(max_length=50)),
                ('descr', models.TextField()),
                ('dosage', models.FloatField()),
                ('dosageUnit', models.CharField(max_length=5)),
                ('feedTime', models.TimeField()),
                ('nextDose', models.DateTimeField()),
                ('forPet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_for_pet', to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=50)),
                ('descr', models.TextField()),
                ('amount', models.FloatField()),
                ('amountUnit', models.CharField(max_length=5)),
                ('feedTime', models.TimeField()),
                ('forPet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_for_pet', to='pet.pet')),
            ],
        ),
    ]
