# Generated by Django 5.2.8 on 2025-12-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='feedTime',
        ),
        migrations.AlterField(
            model_name='food',
            name='descr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='feedTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='descr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='nextDose',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='belongsToBusiness',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='belongsToHouse',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='exerciseReq',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
