# Generated by Django 5.2.8 on 2025-12-11 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_remove_medication_feedtime_alter_food_descr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='belongsToBusiness',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='belongsToHouse',
        ),
    ]
