# Generated by Django 5.2.8 on 2025-12-11 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_remove_pet_belongstobusiness_and_more'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='belongsToBusiness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='registration.business'),
        ),
        migrations.AddField(
            model_name='pet',
            name='belongsToHouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household', to='registration.household'),
        ),
    ]
