# Generated by Django 5.2.8 on 2025-12-11 05:37
# Generated by Django 5.2.8 on 2025-12-11 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('businessID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('businessName', models.CharField(max_length=255)),
                ('streetNo', models.IntegerField()),
                ('streetName', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('payDetail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('houseID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('houseName', models.CharField(max_length=255)),
                ('houseNo', models.IntegerField()),
                ('streetName', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('postcode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PetCarer',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('payDetail', models.CharField(blank=True, max_length=255, null=True)),
                ('belongsToBusiness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_members', to='registration.business')),
                ('belongsToHouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_members', to='registration.household')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='accountManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_households', to='registration.petcarer'),
        ),
        migrations.AddField(
            model_name='business',
            name='accountManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_businesses', to='registration.petcarer'),
        ),
    ]
