# Generated by Django 5.2.8 on 2025-12-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_age_alter_profile_bio'),
        ('user_profile', '0002_alter_profile_bio'),
    ]

    operations = [
    ]
